# Read the Docs configuration file.
# See
# https://docs.readthedocs.io/en/stable/config-file/v2.html

# Version of the .readthedocs.yaml config file.
version: 2

build:
  os: "ubuntu-22.04"
  tools:
    python: "3.9"

python:
  install:
    - requirements: "requirements.txt"
    - requirements: "docs/requirements-docs.txt"
    # Install the project itself.
    - method: "pip"
      path: "."

sphinx:
  builder: "html"
  configuration: "docs/source/conf.py"
  fail_on_warning: true
