# GitHub issue from for bug reports.
# See
# https://docs.github.com/en/communities/using-templates-to-encourage-useful-issues-and-pull-requests/configuring-issue-templates-for-your-repository#creating-issue-forms=

name: "Bug report"
description: "Submit a bug report."
title: "[Bug]: Descriptive title"
labels: ["bug"]
body:
  - type: "markdown"
    attributes:
      value: "Thank you for taking the time to report a bug!"
  - type: "input"
    id: "mdtools_version"
    attributes:
      label: "MDTools version"
      description: |
        Your MDTools version.
        You can check your MDTools version via
        "python3 -c 'import mdtools; print(mdtools.__version__)'"
      placeholder: "Example: 0.2.1.dev3"
    validations:
      required: true
  - type: "input"
    id: "python_version"
    attributes:
      label: "Python version"
      description: |
        Your Python version.
        You can check your Python version via
        "python3 --version"
      placeholder: "Example: 3.8.10"
    validations:
      required: true
  - type: "input"
    id: "os_version"
    attributes:
      label: "Operating system"
      description: "Your operating system."
      placeholder: "Example: Ubuntu 20.04.2 LTS 64-bit"
    validations:
      required: true
  - type: "textarea"
    id: "expected_behavior"
    attributes:
      label: "Expected behavior"
      description: |
        A clear and concise description of what are you expecting to happen.
      placeholder: "When I do this, I expect that."
    validations:
      required: true
  - type: "textarea"
    id: "actual_behavior"
    attributes:
      label: "Actual behavior"
      description: |
        A clear and concise description of what is actually happening.
      placeholder: "When I do this, it happens that."
    validations:
      required: true
  - type: "textarea"
    id: "reproduction"
    attributes:
      label: "Steps to reproduce"
      description: >
        Steps to reproduce the bug.  Optimally, provide a minimal working
        example.
      placeholder: |
         1. Do this.
         2. Do that.
         3. See the bug.
    validations:
      required: true
  - type: "textarea"
    id: "bug_location"
    attributes:
      label: "Supposed bug location"
      description: "Where do you suppose the bug to be?"
      placeholder: |
        In line XY of the script `contact_hist.py`
        Somewhere in the function `mdtools.structure.contact_matrix`
        etc.
    validations:
      required: false
  - type: "textarea"
    id: "solution"
    attributes:
      label: "Possible solution"
      description: "Can you propose a solution for the bug?"
    validations:
      required: false
  - type: "textarea"
    id: "additional_context"
    attributes:
      label: "Additional context"
      description: "Add any other context and additional information here."
    validations:
      required: false
