# GitHub issue form for documentation requests.
# See
# https://docs.github.com/en/communities/using-templates-to-encourage-useful-issues-and-pull-requests/configuring-issue-templates-for-your-repository#creating-issue-forms=

name: "Documentation request"
description: "Request a documentation update/change."
title: "[Docs]: Descriptive title"
labels: ["documentation"]
body:
  - type: "markdown"
    attributes:
      value: "Thank you for enhancing MDTools!"
  - type: "textarea"
    id: "motivation"
    attributes:
      label: "Motivation / Context"
      description: "Why is the documentation update/change required?"
      placeholder: |
        * The documentation of X is unclear about Y...
        * The documentation of Z does not fit to the actual behavior...
        etc.
    validations:
      required: true
  - type: "textarea"
    id: "solution"
    attributes:
      label: "Proposed solution"
      description: "Describe the solution you would like to have."
      placeholder: |
        * I want the documentation of X to be more clear about Y...
        * The documentation of Z should describe the actual behavior, i.e. ...
        etc.
    validations:
      required: true
  - type: "textarea"
    id: "alternatives"
    attributes:
      label: "Alternative solutions"
      description: "Describe alternative solutions you have considered."
    validations:
      required: false
  - type: "textarea"
    id: "additional_context"
    attributes:
      label: "Additional context"
      description: "Add any other context and additional information here."
    validations:
      required: false
