# This workflow will install Python dependencies, run tests and lint with a variety of Python versions
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions

name: Tests

on:
  push:
    branches: [ main ]
  pull_request:
    # Check all PR

jobs:
  build:

    runs-on: ubuntu-latest
    strategy:
      fail-fast: true
      matrix:
        python-version: [3.6, 3.7, 3.8]

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        python -m pip install flake8 flake8-docstrings pytest
        python -m pip install numpy
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
    - name: Lint code with flake8
      run: |
        # stop the build if there are Python syntax errors or undefined names
        flake8 . --count --select=E1,E4,E9,F63,F4,F7,F82,W1 --show-source --statistics
        # exit-zero treats all errors as warnings
        flake8 . --count --exit-zero --max-complexity=10 --max-line-length=79 --statistics
    - name: Lint docstrings with flake8
      run: |
        # stop the build if there are missing or malformed docstrings
        flake8 . --count --select=D102 --show-source --statistics --docstring-convention numpy
    - name: Test with pytest
      run: |
        pytest

